version: 1.0.{build}

clone_depth: 1

image: 
  - Visual Studio 2017

platform: 
  - x86   # Win32
  - x64

configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: littleBusters.sln
  verbosity: quiet
